### ISSUE TITLE
GitHub Workflows: Recommend pinning actions by hash, not tag

### ISSUE THREAD

**Issue by andrewpollock** [ossf/wg-best-practices-os-developers#818]
Off the back of https://news.ycombinator.com/item?id=43367987, I think it would be prudent to:

Have

[Source Code Management Platform Configuration Best Practices (Continuous Integration / Continuous Deployment)](https://github.com/ossf/wg-best-practices-os-developers/blob/main/docs/SCM-BestPractices/README.md)

and

[ GitHub Configuration Best Practices (Continuous Integration / Continuous Deployment)](https://github.com/ossf/wg-best-practices-os-developers/blob/main/docs/SCM-BestPractices/github/README.md#continuous-integration--continuous-deployment
)

prominently signpost to the canonical

[Security hardening for GitHub Actions (Using third-party actions)](https://docs.github.com/en/actions/security-for-github-actions/security-guides/security-hardening-for-github-actions#using-third-party-actions)

and that a reference implementation of a CI/CD check for/enforce this be included.

For this, [Gemini cooked up for me this](https://docs.google.com/document/d/1kc6oIcwHGk-tgiEnE7DiH0v357vhAYll5dlZbIQQFGk/edit?tab=t.0):

```yaml
name: Enforce Commit Hash Pinning

on:
  pull_request:
    branches:
      - main # Or your main branch
  push:
    branches:
      - main # Or your main branch

jobs:
  check-pinning:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Find actions pinned by tag
        id: find-tags
        run: |
          TAGGED_ACTIONS=$(grep -rE 'uses: [^@]+@[^0-9a-f]{7,40}' .github/workflows/ | awk -F ':' '{print $2}')
          if [[ -n "$TAGGED_ACTIONS" ]]; then
            echo "::set-output name=tagged_actions::$TAGGED_ACTIONS"
            echo "::set-output name=found::true"
          else
            echo "::set-output name=found::false"
          fi

      - name: Fail if actions are pinned by tag
        if: steps.find-tags.outputs.found == 'true'
        run: |
          echo "Error: Actions must be pinned to a commit hash, not a tag."
          echo "The following actions are pinned by tag:"
          echo "${{ steps.find-tags.outputs.tagged_actions }}"
          exit 1
```
